### ISSUE TITLE
[SITE VENDAS] Alteração da cor Laranja e Fundo PReto

### ISSUE THREAD

**Issue by GamaSistemas** [GamaSistemas/Fox-Cupom#19]
Utilizar o codigo da cor #e45a00 para tonalidade laranja em todo o site.
Utilizar o codigo da cor #333333 para tonalidade de preto no fundo do rodape

**Comment by xxdannilinxx** [comment]
Cores do bootstrap: https://getbootstrap.com/docs/5.0/utilities/colors/
