### ISSUE TITLE
[SITE VENDAS - PAG CATEGORIAS] Mostrar as categorias em caixas com icon e lista

### ISSUE THREAD

**Issue by GamaSistemas** [GamaSistemas/Fox-Cupom#28]
Adicionar titulo: "Encontre cupons de desconto nas principais categorias"

Mostrar as categorias como na imagem: (Icone e Nome) (O Icone seria interessante escolher la no cadastro de categoria)
Abaixo 
Mostrar Titulo: "Lojas exclusivas e populares"
 - Mostrar grade com a logo das empresas como na imagem.
![image](https://user-images.githubusercontent.com/68168643/116730178-92667280-a9be-11eb-9c14-48b44374da29.png)

**Comment by xxdannilinxx** [comment]
https://www.fabiolobo.com.br/copiar-site.html

**Comment by GamaSistemas** [comment]
As imagens das empresas esta mostrando um retangulo atras da logo. Mostrar somente a logo da loja mesmo, mostrar 5 por linha ou mais. de forma que fique bom.
